/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Codigos_Fonte.projeto.lojaInformatica.view;

import Codigos_Fonte.projeto.lojaInformatica.dao.ItemVendaDAO;
import Codigos_Fonte.projeto.lojaInformatica.dao.ProdutoDAO;
import Codigos_Fonte.projeto.lojaInformatica.dao.VendaDAO;
import Codigos_Fonte.projeto.lojaInformatica.model.Cliente;
import Codigos_Fonte.projeto.lojaInformatica.model.ItemVenda;
import Codigos_Fonte.projeto.lojaInformatica.model.Produto;
import Codigos_Fonte.projeto.lojaInformatica.model.Utilitario;
import Codigos_Fonte.projeto.lojaInformatica.model.Venda;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wesleygomesmonteiro
 */
public class FormPagamento extends javax.swing.JFrame {

    Cliente cliente = new Cliente();
    DefaultTableModel carrinho;
    
    
    /**
     * Creates new form FormPagamento
     */
    public FormPagamento() {
        initComponents();
        
        txtDinheiro.setText("0");
        txtCartao.setText("0");
        txtTroco.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDinheiro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCartao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnFinalizarPedido = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOBS = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamento");

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pagamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DINHEIRO:");

        txtDinheiro.setBackground(new java.awt.Color(204, 204, 204));
        txtDinheiro.setFont(new java.awt.Font("Helvetica Neue", 0, 26)); // NOI18N
        txtDinheiro.setForeground(new java.awt.Color(0, 0, 0));
        txtDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDinheiroKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CARTÃO:");

        txtCartao.setBackground(new java.awt.Color(204, 204, 204));
        txtCartao.setFont(new java.awt.Font("Helvetica Neue", 0, 26)); // NOI18N
        txtCartao.setForeground(new java.awt.Color(0, 0, 0));
        txtCartao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCartaoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("TROCO:");

        txtTroco.setBackground(new java.awt.Color(204, 204, 204));
        txtTroco.setFont(new java.awt.Font("Helvetica Neue", 0, 26)); // NOI18N
        txtTroco.setForeground(new java.awt.Color(0, 0, 0));
        txtTroco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTrocoKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("TOTAL:");

        txtTotal.setBackground(new java.awt.Color(204, 204, 204));
        txtTotal.setFont(new java.awt.Font("Helvetica Neue", 0, 26)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 0, 0));
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKeyTyped(evt);
            }
        });

        btnFinalizarPedido.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        btnFinalizarPedido.setText("Finalizar Venda");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("OBS:");

        txtOBS.setBackground(new java.awt.Color(204, 204, 204));
        txtOBS.setColumns(20);
        txtOBS.setForeground(new java.awt.Color(0, 0, 0));
        txtOBS.setRows(5);
        jScrollPane1.setViewportView(txtOBS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(btnFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTroco)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(89, 89, 89)))
                .addComponent(btnFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        // botão finalizar
        
        double pcartao, pdinheiro, totalpago, totalvenda, troco;
        
        pcartao = Double.parseDouble(txtCartao.getText());
        pdinheiro = Double.parseDouble(txtDinheiro.getText());
        
        totalvenda = Double.parseDouble(txtTotal.getText());
        
        totalpago = pcartao + pdinheiro;
        
        if(totalpago < totalvenda){
            JOptionPane.showMessageDialog(null, "O valor pago é menor que o valor da venda!");
        }
        else{
            troco = totalpago - totalvenda;

            txtTroco.setText(String.valueOf(troco));

            Venda objv = new Venda();
            objv.setCliente(cliente);

            // Data da venda
            // CARREGA A DATA ATUAL DO SISTEMA
            Date agora = new Date();

            SimpleDateFormat dataEUA = new SimpleDateFormat("yyyy-MM-dd");
            String dataMySQL = dataEUA.format(agora);

            objv.setData_venda(dataMySQL);

            // Total da Venda e OBS
            objv.setTotal_venda(totalvenda);
            objv.setObs(txtOBS.getText());

            VendaDAO daov = new VendaDAO();
            daov.cadastrarVenda(objv);

            // Retorna ID da ultima venda
            objv.setId(daov.retornaUltimaVenda());

            // Cadastrando produtos na tabela
            for(int i = 0; i < carrinho.getRowCount(); i++){

                int qtd_estoque, qtd_comprada, qtd_atualizada;
                Produto objp = new Produto();
                ProdutoDAO daoproduto = new ProdutoDAO();
                ItemVenda item = new ItemVenda();
                item.setVenda(objv);

                objp.setId(Integer.parseInt(carrinho.getValueAt(i, 0).toString()));
                item.setProduto(objp);
                item.setQtd(Integer.parseInt(carrinho.getValueAt(i, 2).toString()));
                item.setSubtotal(Double.parseDouble(carrinho.getValueAt(i, 4).toString()));

            //Baixa no Estoque
                qtd_estoque = daoproduto.retornaEstoqueAtual(objp.getId());
                qtd_comprada =  Integer.parseInt(carrinho.getValueAt(i, 2).toString());
                qtd_atualizada = qtd_estoque - qtd_comprada;

                daoproduto.baixarEstoque(objp.getId(), qtd_atualizada);

                ItemVendaDAO daoitem = new ItemVendaDAO();
                daoitem.cadastrarVenda(item);

            }

            JOptionPane.showMessageDialog(null, "Venda Registrada com sucesso");
            
            new PontoDeVenda().setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed

    private void txtDinheiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDinheiroKeyTyped
        // Validação Apenas numeros
        
        char validar = evt.getKeyChar();
        
        if ((Character.isLetter(validar) && (validar != KeyEvent.VK_SPACE)) && (validar != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Digite apenas numeros");
        }
    }//GEN-LAST:event_txtDinheiroKeyTyped

    private void txtCartaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCartaoKeyTyped
        // Validação Apenas numeros
        
        char validar = evt.getKeyChar();
        
        if ((Character.isLetter(validar) && (validar != KeyEvent.VK_SPACE)) && (validar != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Digite apenas numeros");
        }
    }//GEN-LAST:event_txtCartaoKeyTyped

    private void txtTrocoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrocoKeyTyped
        // Validação Apenas numeros
        
        char validar = evt.getKeyChar();
        
        if ((Character.isLetter(validar) && (validar != KeyEvent.VK_SPACE)) && (validar != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Digite apenas numeros");
        }
    }//GEN-LAST:event_txtTrocoKeyTyped

    private void txtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyTyped
        // Validação Apenas numeros
        
        char validar = evt.getKeyChar();
        
        if ((Character.isLetter(validar) && (validar != KeyEvent.VK_SPACE)) && (validar != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Digite apenas numeros");
        }
    }//GEN-LAST:event_txtTotalKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCartao;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextArea txtOBS;
    public javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
